SELECT DATE_FORMAT(NOW(),'%y');
SELECT DATE_FORMAT(NOW(),'%Y');
SELECT DATE_FORMAT(NOW(),'%m %Y');
SELECT DATE_FORMAT(NOW(),'%M %Y');
SELECT DATE_FORMAT(NOW(),'%M %d %Y');
SELECT TIME_FORMAT(NOW(),'%H:%i %p');